var characters = [{name: 'Abe',
  email: 'abram.jorgenson@gmail.com',
  character_name: 'Bernie Newman',
  desc : 'Bernie has come to Hollywood to become a movie star.',
  code: '!tB289IMFI29'},
 {name: 'Devin',
  email: 'devinromano12@gmail.com',
  character_name: 'Nat Rankin',
  desc : 'Nat is a character actor who recently appeared in The Sound of Screams as a villain – as usual.',
  code: 'krN8^$*KYF95'},
 {name: 'Asher',
  email: 'ajorgenson13@gmail.com',
  character_name: 'Bobby Treveeno',
  desc : 'Bobby is an entertainer of the old school and can dance, act and sing. However, Bobby’s career is in decline.',
  code: 'pc5Lm026!TG1'},
 {name: 'Andrew',
  email: 'aaholt7@gmail.com',
  character_name: 'Les Tytan',
  desc : 'Les is a mesmerist whose clients have included Charlie Henderson-Plum and Mel Cutter.',
  code: '!ekcGI*63ODb'},
 {name: 'Lauren',
  email: 'lokelsch@gmail.com',
  character_name: 'CJ Vasquez',
  desc : 'One of The Vampire Detective’s co-producers and is keen to make more blockbusters.',
  code: '5@8mTD3d5HbY'},
 {name: 'Ginni',
  email: 'ginni33@gmail.com',
  character_name: 'Hayden Vicars',
  desc : 'Hayden is co- producer of The Vampire Detective, and one of Tom Speed’s closest friends.',
  code: 'Ih9@O2FAkSu$'},
 {name: 'Jon',
  email: 'jonathan.holderby@gmail.com',
  character_name: 'Terry Ford',
  desc : 'Terry has worked in over 100 movies, playing character roles. In The Vampire Detective Terry played “Hatch”, a bodyguard.',
  code: 'iwf&1O7TxHXB'},
 {name: 'Brandon',
  email: 'bearmaness@gmail.com',
  character_name: 'Charlie Henderson-Plum',
  desc : 'Charlie played “Skipper Primley,” The Vampire Detective’s British villain.',
  code: 'o&9wDlC4EF!G'},
 {name: 'Arlo',
  email: 'arlo.carpenter@gmail.com',
  character_name: 'Evrim Meric',
  desc : 'Bit part actor with a minor role (“Cam Nightshade”) in The Vampire Detective. Evrim also works at the Sacre Bleu restaurant.',
  code: 'jQbWA8b&7W@i'},
 {name: 'Taylor',
  email: 'taylor.rockhold@gmail.com',
  character_name: 'Jules Milton',
  desc : 'Manager of Club Hellfire, where The Vampire Detective’s post-Skelly party is being held. Six years ago, Jules was accused of a fire that burned down three sound stages.',
  code: '8Ll18X!7%6!^'},
 {name: 'Eddie',
  email: 'rodriguezjr.eduardo@gmail.com',
  character_name: 'Ghana Moon',
  desc : 'Ghana is one of Hollywood’s most successful screenwriters, and won a Skelly for The Vampire Detective.',
  code: 'C$$mcXop1QP6'},
 {name: 'Steph',
  email: 'stephanie.warren55@gmail.com',
  character_name: 'Morgan Beech',
  desc : 'Star of blockbuster movie The Vampire Detective. Morgan won critical plaudits for playing Kendall Nimitz, the victim’s partner. This was Morgan’s first major role in a movie.',
  code: 'Og98omm*zA1V'},
 {name: 'Angela',
  email: 'angelavkomar@gmail.com',
  character_name: 'Arden Chase',
  desc : 'One of Hollywood’s finest detectives, Detective Chase is well known to the movie community.',
  code: '7L^P3wYRwtm@'},
 {name: 'Tommy',
  email: 'tommymurray1987@gmail.com',
  character_name: 'Mel Cutter',
  desc : 'Mel is the author of “Cutter’s Comments”, a notorious newspaper column in the Hollywood News. In the column, Mel described The Vampire Detective as “limp and tired” and accused Tom Speed of “having all the charisma of a fishbowl”. Mel is a regular feature at post-award parties.',
  code: 'W9IX@BDTtL8&'},
 {name: 'Jeff',
  email: 'jeffgross522@gmail.com',
  character_name: "Ash d'Lessey",
  desc : 'The Vampire Detective’s director and winner of the Best Director award in this year’s Skelly awards.',
  code: '1m*u&NU2^Un7'},
 {name: 'Emily',
  email: 'emily_cordes@yahoo.com',
  character_name: 'Eddie Flax',
  desc : 'Eddie is one of Hollywood’s many agents and does a lot of charity work.',
  code: '4UdZ85r$0*Q5'},
 {name: 'Julia',
  email: 'julia.dean086@gmail.com',
  character_name: 'Val Taylor',
  desc : 'Val both acts and produces. Val was one of The Vampire Detective’s co-producers.',
  code: 'bNk84YNOQl@i'},
 {name: 'Jenn',
  email: 'jennrussell1984@att.net',
  character_name: 'Cass Dockery',
  desc : 'Cass works for a small independent movie financier, but is looking to break into acting.',
  code: 'xuRwY2!@40O!'},
 {name: 'Bebe',
  email: 'bboimbo@gmail.com',
  character_name: 'Lou Egan',
  desc : 'A respected Hollywood film director. Lou was the original director for The Vampire Detective, but was replaced by Ash d’Lessey.',
  code: 'gYaRZ225@TOm'},
 {name: 'TBD',
  email: '',
  character_name: 'Pip Slater',
  desc : 'Pip is one of Hollywood’s many agents and is looking to sign up more clients tonight.',
  code: 'p1yGBeye3Q*k'}]
